---
- hosts: localhost
  become: yes
  become_method: sudo
  
  tasks:
    - name: Update indexes
      apt: 
        update_cache=yes 
        force_apt_get=yes
   
    - name: Install packages
      apt:
        name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release'] 
        state: present
           
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg  

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

    - name: Install Docker CE
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        update_cache: yes

    - name: Install prerequisites for docker-compose
      apt:
        name: ['python3-pip', 'python3-setuptools', 'virtualenv']

    - name: Install docker-compose
      pip:
        name: docker-compose       
